[package]
name = "clearvm"
version = "0.1.0"
authors = ["chiyoku <chiyokuoni@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.7.3"
mio = "0.7.0"
chashmap = "2.2.2"
rand = "0.7.3"

[profile.dev]
opt-level = 1
overflow-checks = false 